### ISSUE TITLE
Оформление репозитория

### ISSUE THREAD

**Issue by tshemsedinov** [Artem-Vladimirov-IP95/sudoku#2]
- [x] Нужно настроить линтер и зарефакторить код
- [x] Добавить `README.md` 1-2 страницы описания проекта и кода
- [x] Добавить лицензию, например MIT

**Comment by Artem-Vladimirov-IP95** [comment]
Добрый день, код прогнал через линтер (Flake8 на Python), внес мелкие поправки:
- поставил пробели перед запятыми и убрал, где она не нужны;
- убрал больше отступы;
- разделил или переписал большие строки кода (где это можно было сделать).
Так же удалил 2 файла, которые просто являлись кусками кода моего проекта.
Добавил лицензию MIT и написал описание проекта.
